title: Zhuangyu Wei's Homepage
page-top-title: Zhuangyu Wei
top-section-bg-text: 
home-subtitle: Zhuangyu Wei&ensp;|&ensp;韦庄禹
copyright-text: '&copy; Zhuangyu Wei September 2025 – Present. All Rights Reserved.'
